In [7]:
import numpy as np

In [4]:
### ARRAYS

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.array([(1,2,3,4,5), (6,7,8,9,10)])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
num_list = [1,2,3,4,5]

np.array(num_list)

array([1, 2, 3, 4, 5])

In [11]:
print(np.array(num_list))

[1 2 3 4 5]


In [12]:
identity_array = np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
np.eye(4) * 7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [25]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [27]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [28]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.random.rand(4)

array([0.61460088, 0.75917877, 0.81355927, 0.69961382])

In [30]:
np.random.rand(4,5)

array([[0.17819683, 0.48718316, 0.98957835, 0.76922397, 0.26019913],
       [0.64807571, 0.53029958, 0.09301489, 0.06735695, 0.41734547],
       [0.55694315, 0.19292541, 0.6457113 , 0.53417386, 0.86575534],
       [0.69825766, 0.25909728, 0.75119608, 0.29352957, 0.16152313]])

In [31]:
np.random.randint(5,40)

31

In [32]:
np.random.randint(1,10,20)

array([3, 4, 4, 3, 2, 8, 7, 8, 7, 3, 2, 2, 5, 4, 8, 1, 1, 4, 2, 2])

In [36]:
import random

random.seed(10)

random.randint(5,40)

7

In [37]:
### DATA SELECTION

In [38]:
array_1d = np.array([1,2,3,4,5])

In [39]:
array_1d[1]

2

In [40]:
array_1d[-1]

5

In [41]:
array_1d[2:4]

array([3, 4])

In [42]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_2d[1][1]

5

In [43]:
array_2d[1]

array([4, 5, 6])

In [45]:
array_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
array_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [47]:
array_2d[:1, :1]

array([[1]])

In [49]:
array_2d[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [50]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [51]:
arr[arr < 6]

array([1, 2, 3, 4, 5])

In [52]:
arr[ arr > 7 ]

array([8, 9])

In [53]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [56]:
arr[(arr % 2 != 0) & (arr >= 5)]

array([5, 7, 9])

In [57]:
arr > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [58]:
arr == 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [59]:
### BASIC ARRAY OPERATIONS

In [60]:
arr1 = np.arange(0,5)
arr2 = np.arange(6,11)

In [61]:
arr1 + arr2

array([ 6,  8, 10, 12, 14])

In [62]:
arr2 - arr1

array([6, 6, 6, 6, 6])

In [63]:
arr1 * arr2

array([ 0,  7, 16, 27, 40])

In [64]:
arr1 / arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [65]:
arr1 ** 2

array([ 0,  1,  4,  9, 16])

In [66]:
np.add(arr1, arr2)

array([ 6,  8, 10, 12, 14])

In [67]:
np.multiply(arr1, arr2)

array([ 0,  7, 16, 27, 40])

In [69]:
np.subtract(arr1, arr2)

array([-6, -6, -6, -6, -6])

In [70]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [71]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [72]:
np.tan(arr2)

array([-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [73]:
np.log(arr2)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [74]:
np.exp(arr2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [75]:
np.power(arr1, arr2)

array([      0,       1,     256,   19683, 1048576])

In [77]:
np.greater(arr1, arr2)

array([False, False, False, False, False])

In [78]:
np.greater(arr2, arr1)

array([ True,  True,  True,  True,  True])

In [79]:
### BASIC STATISTICS

In [80]:
arr = np.arange(0,5)

In [81]:
arr

array([0, 1, 2, 3, 4])

In [82]:
np.std(arr)

1.4142135623730951

In [84]:
arr2 = np.array([[3,4], [5,6]])

np.std(arr2)

1.118033988749895

In [85]:
np.std(arr2, axis=0)

array([1., 1.])

In [86]:
np.std(arr2, axis=1)

array([0.5, 0.5])

In [88]:
np.var(arr)

2.0

In [89]:
np.var(arr2)

1.25

In [90]:
np.mean(arr) == np.average(arr)

True

In [92]:
arr3 = np.array([1,3,6,4,5,7,8])
np.median(arr3)

5.0

In [93]:
sorted(arr3)

[1, 3, 4, 5, 6, 7, 8]

In [94]:
np.mean(arr3)

4.857142857142857

In [95]:
np.min(arr3)

1

In [96]:
np.max(arr3)

8

In [97]:
### DATA MANIPULATION

In [98]:
arr1 = np.arange(0,10)
arr2 = np.array(([1,2,3], [4,5,6], [7,8,9]))

In [99]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.shape(arr1)

(10,)

In [102]:
np.shape(arr2)

(3, 3)

In [103]:
arr2.shape

(3, 3)

In [104]:
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [105]:
arr2_reshaped = arr2.reshape(9,1)

In [106]:
arr2_reshaped

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [107]:
arr2_reshaped.T

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [108]:
arr2_reshaped.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
np.resize(arr2, (1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [110]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
arr1_copy = arr1.copy()
arr1_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
arr1 = np.arange(0,6)
arr2 = np.arange(6,12)

In [113]:
np.copyto(arr1, arr2)

In [114]:
arr1

array([ 6,  7,  8,  9, 10, 11])

In [115]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12]])

In [116]:
arr1
arr2

array([[10, 11, 12]])

In [117]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [119]:
np.concatenate((arr1, arr2.T), axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [120]:
np.concatenate((arr1, arr2), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [121]:
arr1 = np.arange(0,6)

In [122]:
arr2 = np.arange(6,12)

np.column_stack((arr1, arr2))

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [124]:
np.row_stack((arr1, arr2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [125]:
arr1 = np.arange(0,6)
arr1

array([0, 1, 2, 3, 4, 5])

In [126]:
np.split(arr1, 3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [128]:
np.split(arr1, 2)

[array([0, 1, 2]), array([3, 4, 5])]

In [129]:
arr1 = np.arange(0,6)
arr1

array([0, 1, 2, 3, 4, 5])

In [130]:
np.append(arr1, 7)

array([0, 1, 2, 3, 4, 5, 7])

In [131]:
arr = np.array([[1,2,3]])
np.tile(arr,3)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [132]:
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [133]:
arr = np.array([[1,2,3,4,5,3,2,1,3,5,6,7,7,5,9,5]])

np.sort(arr)

array([[1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 7, 7, 9]])

In [134]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [135]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
np.flipud(arr)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [137]:
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])